# Generated by Django 4.0.6 on 2024-05-24 09:21

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_newstag_statistics_subtitle_statistics_subtitle_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст')),
                ('body_en', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Текст')),
                ('body_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Текст')),
                ('body_uz', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
    ]
