# Generated by Django 4.0.6 on 2024-06-22 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_alter_news_text_alter_news_text_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='whatsapp',
            field=models.URLField(null=True, verbose_name='WhatsApp'),
        ),
    ]
