# Generated by Django 4.0.6 on 2024-08-07 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_dynamicpage_body_en_dynamicpage_body_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='director',
            field=models.CharField(max_length=255, null=True, verbose_name='Директор'),
        ),
        migrations.AddField(
            model_name='contact',
            name='director_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Директор'),
        ),
        migrations.AddField(
            model_name='contact',
            name='director_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Директор'),
        ),
        migrations.AddField(
            model_name='contact',
            name='director_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Директор'),
        ),
        migrations.AddField(
            model_name='contact',
            name='work_time',
            field=models.CharField(max_length=255, null=True, verbose_name='Время работы'),
        ),
    ]
