# Generated by Django 4.0.6 on 2024-08-07 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_contact_director_contact_director_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='work_time_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Время работы'),
        ),
        migrations.AddField(
            model_name='contact',
            name='work_time_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Время работы'),
        ),
        migrations.AddField(
            model_name='contact',
            name='work_time_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Время работы'),
        ),
    ]
