# Generated by Django 4.0.6 on 2024-04-08 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0008_tour_description'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.tour', verbose_name='Тур')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_tours', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сохраненный тур',
                'verbose_name_plural': 'Сохраненные туры',
                'db_table': 'saved_tour',
                'unique_together': {('user', 'tour')},
            },
        ),
    ]
