# Generated by Django 4.0.6 on 2024-04-08 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0008_tour_description'),
        ('users', '0002_savedtour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedtour',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_tours', to='tour.tour', verbose_name='Тур'),
        ),
    ]
