# Generated by Django 4.0.6 on 2024-04-08 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0008_tour_description'),
        ('users', '0003_alter_savedtour_tour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая стоимость')),
                ('status', models.CharField(choices=[('moderation', 'На модерации'), ('pre_payment', 'В ожидании оплаты'), ('success', 'Оплачен')], max_length=20, verbose_name='Статус')),
                ('order_file', models.FileField(blank=True, null=True, upload_to='orders/', verbose_name='Файл заказа')),
                ('tarif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='tour.tourtarif', verbose_name='Тариф')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='tour.tour', verbose_name='Тур')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='OrderPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('passport_info', models.CharField(max_length=255, verbose_name='Паспортные данные')),
                ('passport_file', models.FileField(upload_to='passport/', verbose_name='Файл паспорта')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('visa', models.BooleanField(default=False, verbose_name='Нужна виза')),
                ('order_call', models.BooleanField(default=False, verbose_name='Заказать звонок')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='users.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Пассажир',
                'verbose_name_plural': 'Пассажиры',
                'db_table': 'order_person',
            },
        ),
    ]
