# Generated by Django 4.0.6 on 2024-04-10 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_file'),
        ('users', '0004_order_orderperson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderperson',
            name='passport_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.file', verbose_name='Файл паспорта'),
        ),
    ]
