# Generated by Django 4.0.6 on 2024-07-04 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_orderperson_passport_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(default='USD', max_length=3, verbose_name='Валюта'),
        ),
    ]
