# Generated by Django 4.0.6 on 2024-07-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_payment_refund_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('canceled', 'Отменен'), ('moderation', 'На модерации'), ('pre_payment', 'В ожидании оплаты'), ('success', 'Оплачен')], max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Blocked', 'Blocked'), ('Captured', 'Captured'), ('Refunded', 'Refunded'), ('PartiallyRefunded', 'Partially Refunded'), ('Rejected', 'Rejected')], max_length=50),
        ),
    ]
