# Generated by Django 4.0.6 on 2024-04-07 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0005_tour_transfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regiontour',
            name='region',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='region_tours', to='tour.region', verbose_name='Регион'),
        ),
    ]
