# Generated by Django 4.0.6 on 2024-04-07 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0006_alter_regiontour_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourcategory',
            name='tour_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='tour.tourtype', verbose_name='Тип тура'),
        ),
    ]
