# Generated by Django 4.0.6 on 2024-04-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0007_tourcategory_tour_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
