# Generated by Django 4.0.6 on 2025-03-13 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0010_tourdays_subtitle_tourdays_subtitle_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='from_region',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='return_region',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='to_date',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='to_region',
        ),
        migrations.AddField(
            model_name='tour',
            name='period',
            field=models.CharField(choices=[('all', 'Весь год'), ('winter', 'Зима'), ('spring', 'Весна'), ('summer', 'Лето'), ('autumn', 'Осень')], default='all', max_length=255, verbose_name='Период'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='region_five',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tours_region_five', to='tour.region', verbose_name='Город 5'),
        ),
        migrations.AddField(
            model_name='tour',
            name='region_four',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tours_region_four', to='tour.region', verbose_name='Город 4'),
        ),
        migrations.AddField(
            model_name='tour',
            name='region_one',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tours_region_one', to='tour.region', verbose_name='Город 1'),
        ),
        migrations.AddField(
            model_name='tour',
            name='region_three',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tours_region_three', to='tour.region', verbose_name='Город 3'),
        ),
        migrations.AddField(
            model_name='tour',
            name='region_two',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tours_region_two', to='tour.region', verbose_name='Город 2'),
        ),
        migrations.RemoveField(
            model_name='tour',
            name='tour_type',
        ),
        migrations.AddField(
            model_name='tour',
            name='tour_type',
            field=models.ManyToManyField(related_name='tours', to='tour.tourtype', verbose_name='Тип тура'),
        ),
    ]
