# Generated by Django 4.0.6 on 2025-03-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0012_remove_tour_transfer_tour_days_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
